Bump Kotlin Toolchain to 0.11.0-dev-3955

diff --git a/kotlin b/kotlin
--- a/kotlin
+++ b/kotlin
@@ -17,9 +17,9 @@
 set -e -u
 
 # The version of the Kotlin Toolchain (and CLI) distribution to provision and use
-kotlin_cli_version=0.11.0-dev-3945
+kotlin_cli_version=0.11.0-dev-3955
 # Establish chain of trust from here by specifying exact checksum of Kotlin Toolchain (and CLI) distribution to be run
-kotlin_cli_sha256=4b016abb6155aeb401835037d94fdfbe5ba7a8bb6925e07bc1e7a35f5650017d
+kotlin_cli_sha256=9c9ab3ab33c352166fadc0efd02c7ba234d545cb4795f966d39828a2d8ceffff
 
 KOTLIN_CLI_DOWNLOAD_ROOT="${KOTLIN_CLI_DOWNLOAD_ROOT:-https://packages.jetbrains.team/maven/p/amper/amper}"
 
@@ -29,6 +29,34 @@ die() {
   echo >&2
   exit 1
 }
+
+# usage: check_sha SOURCE_MONIKER FILE SHA_CHECKSUM SHA_SIZE
+# $1 SOURCE_MONIKER (e.g. url)
+# $2 FILE
+# $3 SHA hex string
+# $4 SHA size in bits (256, 512, ...)
+check_sha() {
+  sha_size=$4
+  if command -v shasum >/dev/null 2>&1; then
+    echo "$3 *$2" | shasum -a "$sha_size" --status -c || {
+      die "ERROR: Checksum mismatch for $2 (downloaded from $1): expected checksum $3 but got $(shasum --binary -a "$sha_size" "$2" | awk '{print $1}')"
+    }
+    return 0
+  fi
+
+  shaNsumCommand="sha${sha_size}sum"
+  if command -v "$shaNsumCommand" >/dev/null 2>&1; then
+    # discard the output as sha*sum may print redundant warnings in some versions
+    echo "$3 *$2" | $shaNsumCommand -w -c >/dev/null 2>&1 || {
+      die "ERROR: Checksum mismatch for $2 (downloaded from $1): expected checksum $3 but got $($shaNsumCommand "$2" | awk '{print $1}')"
+    }
+    return 0
+  fi
+
+  echo "Both 'shasum' and 'sha${sha_size}sum' utilities are missing. Please install one of them"
+  return 1
+}
+
 
 download_and_extract() {
   moniker="$1"
@@ -150,33 +178,6 @@ EOF
 
   echo "Download complete."
   echo
-}
-
-# usage: check_sha SOURCE_MONIKER FILE SHA_CHECKSUM SHA_SIZE
-# $1 SOURCE_MONIKER (e.g. url)
-# $2 FILE
-# $3 SHA hex string
-# $4 SHA size in bits (256, 512, ...)
-check_sha() {
-  sha_size=$4
-  if command -v shasum >/dev/null 2>&1; then
-    echo "$3 *$2" | shasum -a "$sha_size" --status -c || {
-      die "ERROR: Checksum mismatch for $2 (downloaded from $1): expected checksum $3 but got $(shasum --binary -a "$sha_size" "$2" | awk '{print $1}')"
-    }
-    return 0
-  fi
-
-  shaNsumCommand="sha${sha_size}sum"
-  if command -v "$shaNsumCommand" >/dev/null 2>&1; then
-    # discard the output as sha*sum may print redundant warnings in some versions
-    echo "$3 *$2" | $shaNsumCommand -w -c >/dev/null 2>&1 || {
-      die "ERROR: Checksum mismatch for $2 (downloaded from $1): expected checksum $3 but got $($shaNsumCommand "$2" | awk '{print $1}')"
-    }
-    return 0
-  fi
-
-  echo "Both 'shasum' and 'sha${sha_size}sum' utilities are missing. Please install one of them"
-  return 1
 }
 
 
