Replace `amper` to `kotlin` wrapper

diff --git a/kotlin b/kotlin
--- a/kotlin
+++ b/kotlin
@@ -5,23 +5,23 @@
 #
 
 # Possible environment variables:
-#   AMPER_DOWNLOAD_ROOT        Maven repository to download Amper dist from.
-#                              default: https://packages.jetbrains.team/maven/p/amper/amper
-#   AMPER_JRE_DOWNLOAD_ROOT    Url prefix to download Amper JRE from.
-#                              default: https:/
-#   AMPER_BOOTSTRAP_CACHE_DIR  Cache directory to store extracted JRE and Amper distribution
-#   AMPER_JAVA_HOME            JRE to run Amper itself (optional, does not affect compilation)
-#   AMPER_JAVA_OPTIONS         JVM options to pass to the JVM running Amper (does not affect the user's application)
-#   AMPER_NO_WELCOME_BANNER    Disables the first-run welcome message if set to a non-empty value
+#   KOTLIN_CLI_DOWNLOAD_ROOT        Maven repository to download the Kotlin CLI dist from.
+#                                     default: https://packages.jetbrains.team/maven/p/amper/amper
+#   KOTLIN_CLI_JRE_DOWNLOAD_ROOT    Url prefix to download the JRE to run the Kotlin CLI
+#                                     default: https:/
+#   KOTLIN_CLI_BOOTSTRAP_CACHE_DIR  Cache directory to store the extracted JRE and Kotlin CLI distribution
+#   KOTLIN_CLI_JAVA_HOME            JRE to run the Kotlin CLI itself (optional, does not affect compilation)
+#   KOTLIN_CLI_JAVA_OPTIONS         JVM options to pass to the JVM running the Kotlin CLI (does not affect the user's application)
+#   KOTLIN_CLI_NO_WELCOME_BANNER    Disables the first-run welcome message if set to a non-empty value
 
 set -e -u
 
-# The version of the Amper distribution to provision and use
-amper_version=0.11.0-dev-3937
-# Establish chain of trust from here by specifying exact checksum of Amper distribution to be run
-amper_sha256=44aac0b8766dc9904f7fc60a950bdc8bdfdae5414b8875a7fc1e9238a7dff5d3
+# The version of the Kotlin Toolchain (and CLI) distribution to provision and use
+kotlin_cli_version=0.11.0-dev-3940
+# Establish chain of trust from here by specifying exact checksum of Kotlin Toolchain (and CLI) distribution to be run
+kotlin_cli_sha256=9052a6e5f5d5b60f2f80b186cc0e5482208d1f995f40ae42d9567d55726fa15b
 
-AMPER_DOWNLOAD_ROOT="${AMPER_DOWNLOAD_ROOT:-https://packages.jetbrains.team/maven/p/amper/amper}"
+KOTLIN_CLI_DOWNLOAD_ROOT="${KOTLIN_CLI_DOWNLOAD_ROOT:-https://packages.jetbrains.team/maven/p/amper/amper}"
 
 die() {
   echo >&2
@@ -55,7 +55,7 @@ download_and_extract() {
     lock_owner=$(cat "$download_lock_file" 2>/dev/null || true)
     # We use `kill -0` instead of `ps -p` as the first one is more portable
     if [ -n "$lock_owner" ] && kill -0 "$lock_owner" >/dev/null; then
-      echo "Another Amper instance (pid $lock_owner) is downloading $moniker. Awaiting the result..."
+      echo "Another Kotlin CLI instance (pid $lock_owner) is downloading $moniker. Awaiting the result..."
       sleep 1
     elif [ -n "$lock_owner" ] && [ "$(cat "$download_lock_file" 2>/dev/null)" = "$lock_owner" ]; then
       rm -f "$download_lock_file"
@@ -63,7 +63,7 @@ download_and_extract() {
       # which means the 'rm' command above from another script could delete our new valid lock file. Instead, we just
       # ask the user to try again. This doesn't 100% eliminate the race, but the probability of issues is drastically
       # reduced because it would involve 4 processes with perfect timing. We can revisit this later.
-      die "Another Amper instance (pid $lock_owner) locked the download of $moniker, but is no longer running. The lock file is now removed, please try again."
+      die "Another Kotlin CLI instance (pid $lock_owner) locked the download of $moniker, but is no longer running. The lock file is now removed, please try again."
     fi
   done
 
@@ -83,19 +83,25 @@ download_and_extract() {
     return 0;
   fi
 
-  if [ "$show_banner_on_cache_miss" = "true" ] && [ -z "${AMPER_NO_WELCOME_BANNER:-}" ]; then
+  if [ "$show_banner_on_cache_miss" = "true" ] && [ -z "${KOTLIN_CLI_NO_WELCOME_BANNER:-}" ]; then
       echo
-      echo '        _____  Welcome to                                  '
-      echo '       /:::::|  ____   ___     ____      ____    __  ___   '
-      echo '      /::/|::| |::::\_|:::\   |:::::\   /::::\  |::|/:::|  '
-      echo '     /::/ |::| |::|\:::|\::\  |::|\::\ /:/__\:\ |:::/      '
-      echo '    /::/__|::| |::| |::| |::| |::| |::|:::::::/ |::|       '
-      echo '   /:::::::::| |::| |::| |::| |::|/::/ \::\__   |::|       '
-      echo '  /::/    |::| |::| |::| |::| |:::::/   \::::|  |::|       '
-      echo '                              |::|                         '
-      echo "                              |::|  v.$amper_version       "
+      cat <<EOF
+Welcome to
+
+@@@        @@@@                               @@@    @@@
+@@@      @@@@                       @@@       @@@    @@@
+@@@    #@@@"                       ,@@@       @@@
+@@@  ,@@@%         ,@@@@@@@,     @@@@@@@@@@   @@@    @@@    @@@  ,@@@@@,
+@@@ @@@@         @@@@@%"%@@@@@   @@@@@@@@@@   @@@    @@@    @@@@@@%%@@@@@
+@@@@@@%         @@@%       %@@@     @@@       @@@    @@@    @@@@      %@@%
+@@@ @@@@=      #@@@         @@@#    @@@       @@@    @@@    @@@        @@@
+@@@   @@@@     #@@@         @@@#    @@@       @@@    @@@    @@@        @@@
+@@@    *@@@%    @@@@       @@@@     @@@       @@@    @@@    @@@        @@@
+@@@      %@@@=   %@@@@*,*@@@@%      @@@@###   @@@    @@@    @@@        @@@
+@@@        @@@@    "@@@@@@@"         %@@@@@   @@@    @@@    @@@        @@@
+EOF
       echo
-      echo "This is the first run of this version, so we need to download the actual Amper distribution."
+      echo "This is the first run of the Kotlin CLI v$kotlin_cli_version, so we need to download the Kotlin Toolchain."
       echo "Please give us a few seconds, subsequent runs will be faster."
       echo
   fi
@@ -112,7 +118,7 @@ download_and_extract() {
     if [ -t 1 ]; then WGET_PROGRESS=""; else WGET_PROGRESS="-nv"; fi
     wget $WGET_PROGRESS --tries=5 --connect-timeout=30 --read-timeout=120 -O "${temp_file}" "$file_url"
   else
-    die "ERROR: Please install 'wget' or 'curl', as Amper needs one of them to download $moniker"
+    die "ERROR: Please install 'wget' or 'curl', as one of them is required to download $moniker"
   fi
 
   check_sha "$file_url" "$temp_file" "$file_sha" "$sha_size"
@@ -125,13 +131,13 @@ download_and_extract() {
       if command -v unzip >/dev/null 2>&1; then
         unzip -q "$temp_file" -d "$extract_dir"
       else
-        die "ERROR: Please install 'unzip', as Amper needs it to extract $moniker"
+        die "ERROR: Please install 'unzip', which is required to extract $moniker"
       fi ;;
     *)
       if command -v tar >/dev/null 2>&1; then
         tar -x -f "$temp_file" -C "$extract_dir"
       else
-        die "ERROR: Please install 'tar', as Amper needs it to extract $moniker"
+        die "ERROR: Please install 'tar', which is required to extract $moniker"
       fi ;;
   esac
 
@@ -183,7 +189,7 @@ find_project_context() {
   this_script="$(realpath "$0")"
   project_dir=$(pwd)
   while [ "$project_dir" != "/" ] && [ -n "$project_dir" ]; do
-    wrapper_candidate="$project_dir/amper"
+    wrapper_candidate="$project_dir/kotlin"
     if [ "$this_script" = "$wrapper_candidate" ]; then
       # Found itself (local wrapper case), no need to update any version or search further.
       return 1
@@ -200,7 +206,7 @@ find_project_context() {
       fi
     elif [ -f "$project_dir/project.yaml" ]; then
       # Found project.yaml but no executable wrapper alongside it
-      echo "WARNING: Found a project.yaml in '$project_dir', but the wrapper script is missing; using $amper_version." >&2
+      echo "WARNING: Found a project.yaml in '$project_dir', but the wrapper script is missing; using Kotlin Toolchain v$kotlin_cli_version." >&2
       return 1
     fi
 
@@ -212,32 +218,32 @@ find_project_context() {
 }
 
 parse_project_context() {
-  # Parse amper_version and amper_sha256 from "$wrapper_script" without executing it.
-  parsed_amper_version=$(
-    sed -n 's/^amper_version=\([A-Za-z0-9._+-]\{1,\}\)[[:space:]]*$/\1/p' "$wrapper_script" \
+  # Parse kotlin_cli_version and kotlin_cli_sha256 from "$wrapper_script" without executing it.
+  parsed_kotlin_cli_version=$(
+    sed -n 's/^kotlin_cli_version=\([A-Za-z0-9._+-]\{1,\}\)[[:space:]]*$/\1/p' "$wrapper_script" \
       | head -n 1
   )
-  parsed_amper_sha256=$(
-    sed -n 's/^amper_sha256=\([0-9a-fA-F]\{64\}\)[[:space:]]*$/\1/p' "$wrapper_script" \
+  parsed_kotlin_cli_sha256=$(
+    sed -n 's/^kotlin_cli_sha256=\([0-9a-fA-F]\{64\}\)[[:space:]]*$/\1/p' "$wrapper_script" \
       | head -n 1
   )
 
-  if [ -z "$parsed_amper_version" ]; then
+  if [ -z "$parsed_kotlin_cli_version" ]; then
     echo "ERROR: Suspicious local wrapper script: failed to detect the distribution version in '$wrapper_script'" >&2
     return 1
   fi
-  if [ -z "$parsed_amper_sha256" ]; then
+  if [ -z "$parsed_kotlin_cli_sha256" ]; then
     echo "ERROR: Suspicious local wrapper script: failed to detect the distribution checksum in '$wrapper_script'" >&2
     return 1
   fi
 
   # overwrite builtin values and proceed
-  amper_version=$parsed_amper_version
-  amper_sha256=$parsed_amper_sha256
+  kotlin_cli_version=$parsed_kotlin_cli_version
+  kotlin_cli_sha256=$parsed_kotlin_cli_sha256
   return 0
 }
 
-if [ -z "${AMPER_WRAPPER_ALWAYS_USE_INTRINSIC_VERSION:-}" ]; then
+if [ -z "${KOTLIN_CLI_WRAPPER_ALWAYS_USE_INTRINSIC_VERSION:-}" ]; then
   find_project_context && parse_project_context
 fi
 
@@ -246,16 +252,16 @@ fi
 kernelName=$(uname -s)
 case "$kernelName" in
   Darwin* )
-    default_amper_cache_dir="$HOME/Library/Caches/JetBrains/Amper"
+    default_kotlin_cli_cache_dir="$HOME/Library/Caches/JetBrains/Kotlin/cli"
     ;;
   Linux* )
-    default_amper_cache_dir="$HOME/.cache/JetBrains/Amper"
+    default_kotlin_cli_cache_dir="$HOME/.cache/JetBrains/Kotlin/cli"
     ;;
   CYGWIN* | MSYS* | MINGW* )
     if command -v cygpath >/dev/null 2>&1; then
-      default_amper_cache_dir=$(cygpath -u "$LOCALAPPDATA\JetBrains\Amper")
+      default_kotlin_cli_cache_dir=$(cygpath -u "$LOCALAPPDATA\JetBrains\Kotlin\cli")
     else
-      die "The 'cypath' command is not available, but Amper needs it. Use amper.bat instead, or try a Cygwin or MSYS environment."
+      die "The 'cypath' command is not available, but the Kotlin CLI needs it. Use kotlin.bat instead, or try a Cygwin or MSYS environment."
     fi
     ;;
   *)
@@ -263,17 +269,17 @@ case "$kernelName" in
     ;;
 esac
 
-amper_cache_dir="${AMPER_BOOTSTRAP_CACHE_DIR:-$default_amper_cache_dir}"
+kotlin_cli_cache_dir="${KOTLIN_CLI_BOOTSTRAP_CACHE_DIR:-$default_kotlin_cli_cache_dir}"
 
-# ********** Provision Amper distribution **********
+# ********** Provision the Kotlin Toolchain distribution **********
 
-amper_url="$AMPER_DOWNLOAD_ROOT/org/jetbrains/amper/amper-cli/$amper_version/amper-cli-$amper_version-dist.tgz"
-amper_target_dir="$amper_cache_dir/amper-cli-$amper_version"
-download_and_extract "Amper distribution v$amper_version" "$amper_url" "$amper_sha256" 256 "$amper_cache_dir" "$amper_target_dir" "true"
+kotlin_cli_url="$KOTLIN_CLI_DOWNLOAD_ROOT/org/jetbrains/kotlin/kotlin-cli/$kotlin_cli_version/kotlin-cli-$kotlin_cli_version-dist.tgz"
+kotlin_cli_target_dir="$kotlin_cli_cache_dir/kotlin-cli-$kotlin_cli_version"
+download_and_extract "Kotlin Toolchain distribution v$kotlin_cli_version" "$kotlin_cli_url" "$kotlin_cli_sha256" 256 "$kotlin_cli_cache_dir" "$kotlin_cli_target_dir" "true"
 
-# ********** Launch Amper **********
+# ********** Launch the Kotlin CLI **********
 
-launcher_script="$amper_target_dir/bin/launcher.sh"
+launcher_script="$kotlin_cli_target_dir/bin/launcher.sh"
 
-AMPER_WRAPPER_PATH="$(realpath "$0")" \
+KOTLIN_CLI_WRAPPER_PATH="$(realpath "$0")" \
 exec /bin/sh "$launcher_script" "$@"
